# Generated by Django 4.2.4 on 2024-07-07 07:03

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spacePick', '0001_add_User'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apod',
            fields=[
                ('apod_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='APODタイトル')),
                ('explanation', models.TextField(blank=True, verbose_name='APOD説明')),
                ('date', models.DateField(verbose_name='APODリクエスト日')),
                ('url', models.URLField(blank=True, verbose_name='APODURL')),
                ('delete_flg', models.BooleanField(default=False, verbose_name='論理削除')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新日時')),
            ],
        ),
    ]
