# Generated by Django 4.2.4 on 2024-07-07 07:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spacePick', '0002_add_APOD'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('like_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delete_flg', models.BooleanField(default=False, verbose_name='論理削除')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新日時')),
                ('apod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spacePick.apod', verbose_name='APODID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spacePick.users', verbose_name='ユーザーID')),
            ],
        ),
    ]
