# Generated by Django 4.2.4 on 2024-07-07 07:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spacePick', '0003_add_Likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apod_vote',
            fields=[
                ('apod_vote_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vote_flg', models.BooleanField(default=False, verbose_name='投票フラグ')),
                ('vote_date', models.DateTimeField(verbose_name='投票日時')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新日時')),
                ('apod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spacePick.apod', verbose_name='APODID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spacePick.users', verbose_name='ユーザーID')),
            ],
        ),
    ]
